![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references. You will work on your own but remember the teaching staff is at your service whenever you encounter problems.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here

np.__version__

'1.19.3'

#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [11]:
# Method 1

a_1=np.random.random(size=(3,2,5))

In [12]:
# Method 2

a_2=np.random.rand(3,2,5)

In [13]:
# Method 3

a_3=np.random.randint(0,100000,(3,2,5))

#### 4. Print *a*.


In [18]:
# your code here

print(f'a_1:\n{a_1}\n\n\na_2:\n{a_2}\n\n\na_3:\n{a_3}')

a_1:
[[[0.96559015 0.44830045 0.31190303 0.32885765 0.56156619]
  [0.70238876 0.10900979 0.51243491 0.59653878 0.32772106]]

 [[0.33227498 0.36665817 0.20419548 0.08129464 0.90900138]
  [0.62713682 0.63771999 0.25703794 0.74223244 0.61041338]]

 [[0.90115216 0.02575759 0.21242379 0.8891695  0.12169717]
  [0.61796788 0.27256403 0.72810339 0.84411114 0.57273233]]]


a_2:
[[[0.02142773 0.50351605 0.77186963 0.04356454 0.76578057]
  [0.34499923 0.13001016 0.76002483 0.36211246 0.53625252]]

 [[0.69267847 0.04745898 0.43841209 0.2306693  0.77030206]
  [0.33290268 0.90760815 0.8627367  0.840091   0.50268004]]

 [[0.95650287 0.87068327 0.62075954 0.59216247 0.45793501]
  [0.2805076  0.47404806 0.94866606 0.4073883  0.10825538]]]


a_3:
[[[43807  5733 67187 95284 20303]
  [30933 41051 46266 21262  1028]]

 [[37599 41658 22471 12810 72282]
  [53581 59863 36649 95720 97571]]

 [[59472 71972 71562 45451 85927]
  [92016 46151  5373 33836 46983]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [30]:
# your code here

b=np.random.randint(0,10,(5,2,3))
b[:,:,:]=1

#### 6. Print *b*.


In [31]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [27]:
# your code here

a_1.shape==b.shape

False

#### 8. Are you able to add *a* and *b*? Why or why not?


In [28]:
# your answer here
a_1+b

#As arrays não tem as mesmas dimensões

ValueError: operands could not be broadcast together with shapes (3,2,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [32]:
# your code here

c=b.reshape(3,2,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# your code/answer here

d=a_1+c

#Agora as arrays tem as mesmas dimensões, por isso, conseguem ser somadas

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [40]:
# your code/answer here

print(f'a:\n{a_1}\n\n\nd:\n{d}')

a:
[[[0.96559015 0.44830045 0.31190303 0.32885765 0.56156619]
  [0.70238876 0.10900979 0.51243491 0.59653878 0.32772106]]

 [[0.33227498 0.36665817 0.20419548 0.08129464 0.90900138]
  [0.62713682 0.63771999 0.25703794 0.74223244 0.61041338]]

 [[0.90115216 0.02575759 0.21242379 0.8891695  0.12169717]
  [0.61796788 0.27256403 0.72810339 0.84411114 0.57273233]]]


d:
[[[1.96559015 1.44830045 1.31190303 1.32885765 1.56156619]
  [1.70238876 1.10900979 1.51243491 1.59653878 1.32772106]]

 [[1.33227498 1.36665817 1.20419548 1.08129464 1.90900138]
  [1.62713682 1.63771999 1.25703794 1.74223244 1.61041338]]

 [[1.90115216 1.02575759 1.21242379 1.8891695  1.12169717]
  [1.61796788 1.27256403 1.72810339 1.84411114 1.57273233]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here

e=a_1*c

#### 13. Does *e* equal to *a*? Why or why not?


In [42]:
# your code/answer here

print(e)

#Sim, e é igual a "a", porque todo elemento multiplicado por 1 resulta nele mesmo

[[[0.96559015 0.44830045 0.31190303 0.32885765 0.56156619]
  [0.70238876 0.10900979 0.51243491 0.59653878 0.32772106]]

 [[0.33227498 0.36665817 0.20419548 0.08129464 0.90900138]
  [0.62713682 0.63771999 0.25703794 0.74223244 0.61041338]]

 [[0.90115216 0.02575759 0.21242379 0.8891695  0.12169717]
  [0.61796788 0.27256403 0.72810339 0.84411114 0.57273233]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [43]:
# your code here

d_max=d.max()
d_min=d.min()
d_mean=d.mean()

print(d_max,d_min,d_mean)

1.9655901500811923 1.025757588265078 1.4939318333290355


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [54]:
# your code here

f=np.empty((3,2,5), float)
print(f)

[[[0.96559015 0.44830045 0.31190303 0.32885765 0.56156619]
  [0.70238876 0.10900979 0.51243491 0.59653878 0.32772106]]

 [[0.33227498 0.36665817 0.20419548 0.08129464 0.90900138]
  [0.62713682 0.63771999 0.25703794 0.74223244 0.61041338]]

 [[0.90115216 0.02575759 0.21242379 0.8891695  0.12169717]
  [0.61796788 0.27256403 0.72810339 0.84411114 0.57273233]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [62]:
# your code here

#print(f'd:\n{d}')

d.shape[0]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_max:
                f[i,j,k]=100
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]<d_mean and d[i,j,k]>d_min:
                f[i,j,k]=25

#print(f'\n\nf:\n{f}')

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],

[[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],

[[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
 [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
```

In [63]:
# your code here

print(f'd:\n{d}')
print(f'\n\nf:\n{f}')

d:
[[[1.96559015 1.44830045 1.31190303 1.32885765 1.56156619]
  [1.70238876 1.10900979 1.51243491 1.59653878 1.32772106]]

 [[1.33227498 1.36665817 1.20419548 1.08129464 1.90900138]
  [1.62713682 1.63771999 1.25703794 1.74223244 1.61041338]]

 [[1.90115216 1.02575759 1.21242379 1.8891695  1.12169717]
  [1.61796788 1.27256403 1.72810339 1.84411114 1.57273233]]]


f:
[[[100.  25.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 75.   0.  25.  75.  25.]
  [ 75.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here

## Additional Challenges for the Nerds

If you are way ahead of your classmates and willing to accept some tough challenges about Numpy, take one or several of the following Codewar *katas*. 	You need to already possess a good amount of knowledge in Python and statistics because you will need to write Python functions, do loops, write conditionals, and deal with matrices.

* [Insert dashes](https://www.codewars.com/kata/insert-dashes)
* [Thinkful - Logic Drills: Red and bumpy](https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy)